### ISSUE TITLE
Match react-bootstrap page layout api 

### ISSUE THREAD

**Issue by patrickleet** [blueberryapps/radium-bootstrap-grid#4]
https://react-bootstrap.github.io/components.html#page-layout

Love where this project is headed. Great start!

I was hoping to find something like this to replace my current use of react-bootstrap page layout.
Looks like it's missing a few things to be complete though. Namely offsets, and helpers like "xsHidden".

What are your plans for this repo?

**Comment by geoRG77** [comment]
@patrickleet We plan to improve this project but somehow I didn't expect it to have much success as I wasn't sure if we shouldn't focus on flex-based grid systems instead.

Any help is appreciated! :)

**Comment by geoRG77** [comment]
@patrickleet This version https://github.com/blueberryapps/radium-bootstrap-grid/releases/tag/0.1.0 has new API and adds missing features.

**Comment by patrickleet** [comment]
nice, thanks!
